name: Trigger Tests

on:
  push:
    branches:
      - main

jobs:
  trigger-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Tests Workflow
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.TESTS_REPOSITORY_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Type: application/json" \
            -d '{"event_type": "workflow_dispatch"}' \
            "https://api.github.com/repos/almalmalm/my-expenses-tests/dispatches"
