name: Integration Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout my-expenses
        uses: actions/checkout@v3

      - name: Checkout my-expenses-tests
        uses: actions/checkout@v3
        with:
          repository: almalmalm/my-expenses-tests
          ref: main

      - name: Run Cypress tests
        run: |
          npm install
          npm test
