name: Integration Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout my-expenses
        uses: actions/checkout@v2

      - name: Checkout my-expenses-tests
        uses: actions/checkout@v2
        with:
          repository: almalmalm/my-expenses-tests
          ref: main
          path: tests

      - name: Run Cypress tests
        run: |
          cd tests
          npm install
          npm run test
