name: Trigger Tests

on:
  push:
    branches:
      - main

jobs:
  trigger-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Tests Workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TESTS_REPOSITORY_PAT }}
          repository: almalmalm/my-expenses-tests
          event-type: run-tests
